"""Daily Drop — one auto-generated "newspaper front page" per day.

A single BROADCAST card (identical for everyone) summarising the day's action:
biggest mover/faceplant, the rarest correct "called it", the tightest rivalry,
and the notable overnight overtakes — all computed from existing leaderboard
snapshots, predictions and scores.

The savage ``roast`` is written SEPARATELY by Claude (on the user's Claude Code
subscription, not a backend API key) and PATCHed in after the stats land, so it
is nullable: the modal renders stats-only until the roast arrives.

One row per ``drop_date`` (UTC). The builder upserts idempotently, mirroring
``LeaderboardSnapshot``.
"""

import uuid
from datetime import date, datetime

from sqlalchemy import JSON, Column, UniqueConstraint
from sqlmodel import Field, SQLModel

from app.models._datetime import utc_datetime_column, utc_now


class DailyDrop(SQLModel, table=True):
    """One day's broadcast Drop: computed stats + (later) a roast."""

    __tablename__ = "daily_drops"
    __table_args__ = (UniqueConstraint("drop_date", name="uq_daily_drop_date"),)

    id: uuid.UUID = Field(default_factory=uuid.uuid4, primary_key=True)

    # The UTC calendar day this drop is FOR — built each morning, summarising the
    # prior day's action. Unique: exactly one drop per day.
    drop_date: date = Field(index=True)

    # Computed broadcast stats (mover, faceplant, called_it, rivalry, overtakes).
    # JSON so the card's shape can evolve without a migration per tweak; always
    # reassigned wholesale (never mutated in place), so change-tracking is moot.
    payload: dict = Field(
        default_factory=dict, sa_column=Column(JSON, nullable=False)
    )

    # The savage roast, generated by Claude on the user's subscription and PATCHed
    # in after the stats are computed. Null until then — the modal degrades to
    # stats-only.
    roast: str | None = Field(default=None)
    roast_generated_at: datetime | None = Field(
        default=None, sa_column=utc_datetime_column(nullable=True)
    )

    created_at: datetime = Field(
        default_factory=utc_now, sa_column=utc_datetime_column()
    )
