"""add_phase2_fields_to_competition

Revision ID: 0ecd447ccd5a
Revises: fa36cc119ee8
Create Date: 2026-01-30 21:31:57.877069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0ecd447ccd5a'
down_revision: Union[str, None] = 'fa36cc119ee8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add with server_default for existing rows, then remove default
    op.add_column('competitions', sa.Column('is_phase2_active', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('competitions', sa.Column('phase2_activated_at', sa.DateTime(), nullable=True))
    op.add_column('competitions', sa.Column('phase2_bracket_deadline', sa.DateTime(), nullable=True))
    # Remove server default after column is created (SQLModel handles defaults at app level)
    op.alter_column('competitions', 'is_phase2_active', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('competitions', 'phase2_bracket_deadline')
    op.drop_column('competitions', 'phase2_activated_at')
    op.drop_column('competitions', 'is_phase2_active')
    # ### end Alembic commands ###
