"""add daily_drops table

Revision ID: 2daeac7809a3
Revises: abd779b87c8e
Create Date: 2026-06-15 10:53:38.947714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2daeac7809a3'
down_revision: Union[str, None] = 'abd779b87c8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_drops',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('drop_date', sa.Date(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('roast', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('roast_generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('drop_date', name='uq_daily_drop_date')
    )
    op.create_index(op.f('ix_daily_drops_drop_date'), 'daily_drops', ['drop_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_daily_drops_drop_date'), table_name='daily_drops')
    op.drop_table('daily_drops')
    # ### end Alembic commands ###
