"""add email_sends idempotency table

Revision ID: 536a07516be9
Revises: 5c6e46005455
Create Date: 2026-05-23 21:17:06.765591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '536a07516be9'
down_revision: Union[str, None] = '5c6e46005455'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_sends',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('competition_id', sa.Uuid(), nullable=False),
    sa.Column('deadline_kind', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('resend_message_id', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'competition_id', 'deadline_kind', name='uq_email_send_user_competition_deadline')
    )
    op.create_index(op.f('ix_email_sends_competition_id'), 'email_sends', ['competition_id'], unique=False)
    op.create_index(op.f('ix_email_sends_deadline_kind'), 'email_sends', ['deadline_kind'], unique=False)
    op.create_index(op.f('ix_email_sends_sent_at'), 'email_sends', ['sent_at'], unique=False)
    op.create_index(op.f('ix_email_sends_user_id'), 'email_sends', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_email_sends_user_id'), table_name='email_sends')
    op.drop_index(op.f('ix_email_sends_sent_at'), table_name='email_sends')
    op.drop_index(op.f('ix_email_sends_deadline_kind'), table_name='email_sends')
    op.drop_index(op.f('ix_email_sends_competition_id'), table_name='email_sends')
    op.drop_table('email_sends')
    # ### end Alembic commands ###
