"""add is_ghost flag to users

Revision ID: abd779b87c8e
Revises: b3d9f1a7c2e8
Create Date: 2026-06-12 12:20:42.927549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'abd779b87c8e'
down_revision: Union[str, None] = 'b3d9f1a7c2e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # server_default so existing rows backfill to false; the ORM default
    # covers new rows. (Autogenerate omits this — see CLAUDE.md migrations.)
    op.add_column(
        'users',
        sa.Column('is_ghost', sa.Boolean(), nullable=False, server_default=sa.false()),
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_ghost')
    # ### end Alembic commands ###
