"""add push notification tables

Revision ID: b3d9f1a7c2e8
Revises: ff59fdd71631
Create Date: 2026-06-06 00:00:00.000000

Adds the two Web Push tables:
  - push_subscriptions: one row per device push endpoint
  - push_sends:         idempotency log (mirrors email_sends)

Hand-written (not autogenerated) because the models were added on a
worktree the dev container doesn't mount. Both tables are new/empty, so
this applies cleanly on top of the live schema.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b3d9f1a7c2e8'
down_revision: Union[str, None] = 'ff59fdd71631'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        'push_subscriptions',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('user_id', sa.Uuid(), nullable=False),
        sa.Column('endpoint', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('p256dh', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('auth', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('active', sa.Boolean(), nullable=False),
        sa.Column('user_agent', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('endpoint', name='uq_push_subscription_endpoint'),
    )
    op.create_index(
        op.f('ix_push_subscriptions_active'), 'push_subscriptions', ['active'], unique=False
    )
    op.create_index(
        op.f('ix_push_subscriptions_user_id'), 'push_subscriptions', ['user_id'], unique=False
    )

    op.create_table(
        'push_sends',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('user_id', sa.Uuid(), nullable=False),
        sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
        sa.Column('ref_id', sa.Uuid(), nullable=False),
        sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_id', 'kind', 'ref_id', name='uq_push_send_user_kind_ref'),
    )
    op.create_index(op.f('ix_push_sends_kind'), 'push_sends', ['kind'], unique=False)
    op.create_index(op.f('ix_push_sends_ref_id'), 'push_sends', ['ref_id'], unique=False)
    op.create_index(op.f('ix_push_sends_sent_at'), 'push_sends', ['sent_at'], unique=False)
    op.create_index(op.f('ix_push_sends_user_id'), 'push_sends', ['user_id'], unique=False)


def downgrade() -> None:
    op.drop_index(op.f('ix_push_sends_user_id'), table_name='push_sends')
    op.drop_index(op.f('ix_push_sends_sent_at'), table_name='push_sends')
    op.drop_index(op.f('ix_push_sends_ref_id'), table_name='push_sends')
    op.drop_index(op.f('ix_push_sends_kind'), table_name='push_sends')
    op.drop_table('push_sends')
    op.drop_index(op.f('ix_push_subscriptions_user_id'), table_name='push_subscriptions')
    op.drop_index(op.f('ix_push_subscriptions_active'), table_name='push_subscriptions')
    op.drop_table('push_subscriptions')
