"""add exact_scores and correct_outcomes to leaderboard_snapshots

Revision ID: cadef7c2acd7
Revises: a1f4c9d2e731
Create Date: 2026-05-24 13:24:17.812040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'cadef7c2acd7'
down_revision: Union[str, None] = 'a1f4c9d2e731'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Add the two new counters with a server-side default of 0 so existing
    # snapshot rows backfill cleanly. Historical snapshots predate this
    # feature; we can't reconstruct per-day exact/outcome counts from rank +
    # total alone, so 0 is the honest fallback. New snapshots (taken by
    # take_daily_snapshots from this commit forward) populate the real values.
    op.add_column(
        'leaderboard_snapshots',
        sa.Column('exact_scores', sa.Integer(), nullable=False, server_default='0'),
    )
    op.add_column(
        'leaderboard_snapshots',
        sa.Column('correct_outcomes', sa.Integer(), nullable=False, server_default='0'),
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leaderboard_snapshots', 'correct_outcomes')
    op.drop_column('leaderboard_snapshots', 'exact_scores')
    # ### end Alembic commands ###
