"""add fifa_rankings table

Revision ID: cf53eb42651f
Revises: cadef7c2acd7
Create Date: 2026-05-28 04:26:00.154264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'cf53eb42651f'
down_revision: Union[str, None] = 'cadef7c2acd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fifa_rankings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('country_code', sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False),
    sa.Column('team_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('points', sa.Float(), nullable=False),
    sa.Column('pub_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('country_code', name='uq_fifa_ranking_country_code')
    )
    op.create_index(op.f('ix_fifa_rankings_country_code'), 'fifa_rankings', ['country_code'], unique=False)
    op.create_index(op.f('ix_fifa_rankings_rank'), 'fifa_rankings', ['rank'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fifa_rankings_rank'), table_name='fifa_rankings')
    op.drop_index(op.f('ix_fifa_rankings_country_code'), table_name='fifa_rankings')
    op.drop_table('fifa_rankings')
    # ### end Alembic commands ###
