"""Initial schema

Revision ID: f06b6a2077d3
Revises: 
Create Date: 2026-05-12 21:10:10.641104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f06b6a2077d3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('competitions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('entry_fee', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('phase1_deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_phase2_active', sa.Boolean(), nullable=False),
    sa.Column('phase2_activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('phase2_bracket_deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('phase2_deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('config_file', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('external_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_competitions_external_id'), 'competitions', ['external_id'], unique=False)
    op.create_index(op.f('ix_competitions_name'), 'competitions', ['name'], unique=False)
    op.create_table('fixtures',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('competition_id', sa.Uuid(), nullable=False),
    sa.Column('home_team', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('away_team', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('kickoff', sa.DateTime(timezone=True), nullable=False),
    sa.Column('stage', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('group', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('match_number', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('SCHEDULED', 'LIVE', 'HALFTIME', 'FINISHED', 'POSTPONED', 'CANCELLED', name='matchstatus'), nullable=False),
    sa.Column('minute', sa.Integer(), nullable=True),
    sa.Column('external_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fixtures_away_team'), 'fixtures', ['away_team'], unique=False)
    op.create_index(op.f('ix_fixtures_external_id'), 'fixtures', ['external_id'], unique=False)
    op.create_index(op.f('ix_fixtures_home_team'), 'fixtures', ['home_team'], unique=False)
    op.create_index(op.f('ix_fixtures_kickoff'), 'fixtures', ['kickoff'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('google_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('auth_provider', sa.Enum('EMAIL', 'GOOGLE', name='authprovider'), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('competition_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    op.create_table('match_predictions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('fixture_id', sa.Uuid(), nullable=False),
    sa.Column('home_score', sa.Integer(), nullable=False),
    sa.Column('away_score', sa.Integer(), nullable=False),
    sa.Column('phase', sa.Enum('PHASE_1', 'PHASE_2', name='predictionphase'), nullable=False),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['fixture_id'], ['fixtures.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_match_predictions_fixture_id'), 'match_predictions', ['fixture_id'], unique=False)
    op.create_index(op.f('ix_match_predictions_user_id'), 'match_predictions', ['user_id'], unique=False)
    op.create_table('scores',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('fixture_id', sa.Uuid(), nullable=False),
    sa.Column('home_score', sa.Integer(), nullable=False),
    sa.Column('away_score', sa.Integer(), nullable=False),
    sa.Column('home_score_et', sa.Integer(), nullable=True),
    sa.Column('away_score_et', sa.Integer(), nullable=True),
    sa.Column('home_penalties', sa.Integer(), nullable=True),
    sa.Column('away_penalties', sa.Integer(), nullable=True),
    sa.Column('source', sa.Enum('API', 'MANUAL', name='scoresource'), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['fixture_id'], ['fixtures.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scores_fixture_id'), 'scores', ['fixture_id'], unique=True)
    op.create_table('team_predictions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('team', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('stage', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('group_position', sa.Integer(), nullable=True),
    sa.Column('phase', sa.Enum('PHASE_1', 'PHASE_2', name='predictionphase'), nullable=False),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_team_predictions_team'), 'team_predictions', ['team'], unique=False)
    op.create_index(op.f('ix_team_predictions_user_id'), 'team_predictions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_team_predictions_user_id'), table_name='team_predictions')
    op.drop_index(op.f('ix_team_predictions_team'), table_name='team_predictions')
    op.drop_table('team_predictions')
    op.drop_index(op.f('ix_scores_fixture_id'), table_name='scores')
    op.drop_table('scores')
    op.drop_index(op.f('ix_match_predictions_user_id'), table_name='match_predictions')
    op.drop_index(op.f('ix_match_predictions_fixture_id'), table_name='match_predictions')
    op.drop_table('match_predictions')
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_fixtures_kickoff'), table_name='fixtures')
    op.drop_index(op.f('ix_fixtures_home_team'), table_name='fixtures')
    op.drop_index(op.f('ix_fixtures_external_id'), table_name='fixtures')
    op.drop_index(op.f('ix_fixtures_away_team'), table_name='fixtures')
    op.drop_table('fixtures')
    op.drop_index(op.f('ix_competitions_name'), table_name='competitions')
    op.drop_index(op.f('ix_competitions_external_id'), table_name='competitions')
    op.drop_table('competitions')
    # ### end Alembic commands ###
